package saints_specification_go

const (
	TRANSMIT_MESSAGE_REGISTER_EVENT    = "hello"
	TRANSMIT_MESSAGE_JOINROOM_EVENT    = "join_room"
	TRANSMIT_MESSAGE_LEAVEROOM_EVENT   = "leave_room"
	TRANSMIT_MESSAGE_MESSAGEUP_EVENT   = "message_up"
	TRANSMIT_MESSAGE_MESSAGEDOWN_EVENT = "message_down"

	TRANSMIT_MESSAGE_ROOM_DEVICE_EVENT    = "device_event"
	TRANSMIT_MESSAGE_ROOM_DEVICE_STATUS   = "device_status"
	TRANSMIT_MESSAGE_ROOM_DEVICE_CONTROL  = "device_control"
	TRANSMIT_MESSAGE_ROOM_DIGITAL_CONTROL = "digital_control"
	TRANSMIT_MESSAGE_ROOM_HOSPITAL        = "hospital"
	TRANSMIT_MESSAGE_ROOM_MAINTAIN        = "maintain"
	TRANSMIT_MESSAGE_ROOM_PRISON          = "prison"
	TRANSMIT_MESSAGE_ROOM_BIOIDENTIFY     = "bioidentify"
)
